### ISSUE TITLE
Views in BigQuery

### ISSUE THREAD

**Issue by FawzM** [GoogleCloudPlatform/cloud-data-quality#180]
Hi, maybe this is not the place to ask but I'll ask anyways. When I run cloudDQ, in the BigQuery dataset where it creates the dq_summary table it also creates a lot of views. Is it necessary to have them permanently? I have a lot of rule_bindings so these views take a lot of space which is annoying. Could these views perhaps be temporal?

**Comment by thinhha** [comment]
Hey @FawzM thanks for asking your question and apologies for the delayed response. The BQ dataset containing the dq_summary table is meant for internal usage of CloudDQ code and will contain the views among other tables. We don't have a cleanup logic today and may be able to make the views auto-expiring in the future however this is not prioritized. I wanted to highlight that the views they should not incur any cost to you.
