### ISSUE TITLE
column_id at null in dq_summary In a Rule Type CUSTOM_SQL_STATEMENT

### ISSUE THREAD

**Issue by yankisimo** [GoogleCloudPlatform/cloud-data-quality#198]
In a Rule Type CUSTOM_SQL_STATEMENT, the column_id is always null in dq_summary. 
But in the documentation:

_"The rule binding sets the value of the column parameter through the column_id field and the custom parameters are set explicitly by listing them on each rule reference."_

![image](https://user-images.githubusercontent.com/67339222/197190175-3c5f5a41-6ee0-4892-b401-48257909fc94.png)

**Comment by thinhha** [comment]
Hi @yankisimo the column_id in a CUSTOM_SQL_STATEMENT rule is empty because the rule could in theory reference any columns, not just the column_id field.

The documentation is outdated. Thank you for pointing this out. We will update them.

**Comment by thinhha** [comment]
Documentation updated in https://github.com/GoogleCloudPlatform/cloud-data-quality/pull/200
