### ISSUE TITLE
Broken impersonate account flow

### ISSUE THREAD

**Issue by YungChunLu** [GoogleCloudPlatform/cloud-data-quality#226]
Hi team,

I found an permission issue when using impersonate account. I found that the reason is that the code does not pass the gcp_impersonation_credential at [here](https://github.com/GoogleCloudPlatform/cloud-data-quality/blob/main/clouddq/runners/dbt/dbt_runner.py#L137) when we try to generate the connection config again after we init the dbt runner

**Comment by thinhha** [comment]
Hi @YungChunLu thanks a lot for raising the issue and providing clear information on how to fix it. We've
applied the fix in https://github.com/GoogleCloudPlatform/cloud-data-quality/pull/227 and included it in release 1.0.5.
