### ISSUE TITLE
Unable to run clouddq - FileNotFoundError

### ISSUE THREAD

**Issue by wojtek-szymanski** [GoogleCloudPlatform/cloud-data-quality#34]
I was able to set up my local env based on instruction below:
https://github.com/GoogleCloudPlatform/cloud-data-quality/blob/main/docs/getting-started-with-default-configs.md

However, running _clouddq_ command failed:
`python3 clouddq \
    T2_DQ_1_EMAIL \
    configs \
    --metadata='{"test":"test"}' \
    --dbt_profiles_dir=. \
    --dbt_path=. \
    --environment_target=dev`

> FileNotFoundError: [Errno 2] No such file or directory: '~/dev/mms/cloud-data-quality/env/lib/python3.8/site-packages/dbt_project.yml'

`uname -a`
Darwin mac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
`python3 --version`
Python 3.8.6
`pip --version`
pip 21.1.2 from ~/dev/mms/cloud-data-quality/env/lib/python3.8/site-packages/pip (python 3.8)

**Comment by thinhha** [comment]
Thanks for raising the issue Wojtek. I think I know what's happening and I'm working on a fix.

For now, could you try building the package using `make build` and run CloudDQ using `python3 bazel-bin/clouddq/clouddq_patched.zip --help` instead? We're only running tests on this path right now but we'll add tests on the `pip install` path as well once the fix is applied.

**Comment by wojtek-szymanski** [comment]
Hi Thinh, thanks for your feedback. Running clouddq with bazel distribution is working fine.
I'll keep this ticket open until your PR gets merged.

**Comment by thinhha** [comment]
Hey Wojtek, we've fixed this in v0.2.0. Could you check it out to confirm if it all works?
https://github.com/GoogleCloudPlatform/cloud-data-quality/releases/tag/v0.2.0

Thanks!

**Comment by wojtek-mms** [comment]
Thanks Thinh,  it is working fine now. Please also update MD files:

- README.md: `cp profiles.yml.template profiles.yml` -> `cp dbt/profiles.yml.template dbt/profiles.yml`
- README.md: `--dbt_profiles_dir=.` -> `--dbt_profiles_dir=dbt`
- getting-started-with-default-configs.md: `cp profiles.yml.template profiles.yml` -> `cp dbt/profiles.yml.template dbt/profiles.yml`
- getting-started-with-default-configs.md: `sed -i s/\<your_gcp_project_id\>/${GCP_PROJECT_ID}/g profiles.yml` -> `sed -i s/\<your_gcp_project_id\>/${GCP_PROJECT_ID}/g dbt/profiles.yml`
- getting-started-with-default-configs.md:`--dbt_profiles_dir=.` -> `--dbt_profiles_dir=dbt`

**Comment by thinhha** [comment]
thanks for checking and for the detailed feedback!

Fixed the docs in https://github.com/GoogleCloudPlatform/cloud-data-quality/pull/39.

I'll close this ticket now.
