### ISSUE TITLE
add spark support

### ISSUE THREAD

**Issue by thinhha** [GoogleCloudPlatform/cloud-data-quality#5]

**Comment by thinhha** [comment]
depends on https://github.com/GoogleCloudPlatform/cloud-data-quality/issues/7

**Comment by wojtek-mms** [comment]
Hello, I have found some docs for PySpark and Dataproc:
https://github.com/GoogleCloudPlatform/cloud-data-quality/blob/main/docs/submit-clouddq-as-dataproc-job.md

On the other hand, I could not found any Spark context/session usage. What's the point of running dbt queries via Spark, it's just for convenience purposes? Basically, I did bazel setup on one of my VMs and I wonder what are the other benefits?
As I understood from #7, Spark will be one of the executions engines, but currently only dbt is supported.

**Comment by thinhha** [comment]
Hey @wojtek-mms, this is to support our plan to allow validation of structured data (e.g. Parquet, Avro, ORC) in GCS using dbt-spark via SparkSQL. The Dataproc runtime will be crucial to both connect to the Hive metastore as well as to execute the validation routines via SparkSQL.

Currently, we support validating GCS data using BQ External Tables via dbt-bigquery. Using SparkSQL will enable validation of data types not currently supported by BQ External Tables such as Parquet complex types.

At the moment, deploying on Dataproc is one option among others (e.g. Cloud Composer, Cloud Build, Cloud Workflows, etc...). In the future, we might provide a more streamlined option for users to deploy CloudDQ via Dataproc without managing the underlying cluster.

**Comment by wojtek-mms** [comment]
Hello @thinhha, thanks for clarification.

**Comment by qmqmpzpz** [comment]
gen/front_end/entrypoints/js_app/devtools_entrypoint-entrypoint-typescript-tsconfig.json
gen/front_end/entrypoints/js_app/js_app.d.ts
gen/front_end/entrypoints/js_app/js_app.js
gen/front_end/entrypoints/js_app/js_app.js.map

gen/test/e2e/settings/settings-tsconfig.json
gen/test/e2e/settings/shortcut_settings_test.d.ts
gen/test/e2e/settings/shortcut_settings_test.js
gen/test/e2e/settings/shortcut_settings_test.js.map

**Comment by qmqmpzpz** [comment]
<html>
<body>


6 | gen/test/unittests/front_end/panels/application/components/EndpointsGrid_test.d.tsgen/test/unittests/front_end/panels/application/components/EndpointsGrid_test.jsgen/test/unittests/front_end/panels/application/components/EndpointsGrid_test.js.mapgen/test/unittests/front_end/panels/application/components/FrameDetailsView_test.d.tsgen/test/unittests/front_end/panels/application/components/FrameDetailsView_test.jsgen/test/unittests/front_end/panels/application/components/FrameDetailsView_test.js.mapgen/test/unittests/front_end/panels/application/components/OriginTrialTreeView_test.d.tsgen/test/unittests/front_end/panels/application/components/OriginTrialTreeView_test.jsgen/test/unittests/front_end/panels/application/components/OriginTrialTreeView_test.js.mapgen/test/unittests/front_end/panels/application/components/ReportsGrid_test.d.tsgen/test/unittests/front_end/panels/application/components/ReportsGrid_test.jsgen/test/unittests/front_end/panels/application/components/ReportsGrid_test.js.mapgen/test/unittests/front_end/panels/application/components/StackTrace_test.d.tsgen/test/unittests/front_end/panels/application/components/StackTrace_test.jsgen/test/unittests/front_end/panels/application/components/StackTrace_test.js.mapgen/test/unittests/front_end/panels/application/components/TrustTokensView_test.d.tsgen/test/unittests/front_end/panels/application/components/TrustTokensView_test.jsgen/test/unittests/front_end/panels/application/components/TrustTokensView_test.js.mapgen/test/unittests/front_end/panels/application/components/components-tsconfig.json
-- | --



</body>
</html>

**Comment by ranjitparva** [comment]
I'm looking for the same thing. Is it now supported in dbt-spark?
